version: '3'
services:
    web:
        build: .
        ports:
            - 8000:8000
        networks:
            - default
        depends_on: 
            - redis
        volumes:
            - .:/crossmod

    redis:
        image: redis:5-buster
        command: ["redis-server"]
        hostname: redis
        networks:
            - default
        volumes:
            - redis-data:/data
    
networks:
    default:
        driver: "bridge"

volumes:
    redis-data: {}
