site_name: Crossmod
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Crossmod: 
        - API: crossmod/api.md
        - Database: crossmod/db.md
        - Helpers: crossmod/helpers.md
        - ML: crossmod/ml.md
        - Data Analysis: crossmod/analysis.md
    - Models: models.md
theme: readthedocs