site_name: Crossmod
nav:
    - Home: docs/index.md
    - Getting Started: docs/getting_started.md
    - Crossmod: 
        - 'API': crossmod/api.md
        - 'Database': crossmod/db.md
        - 'Helpers': crossmod/helpers.md
        - 'ML': crossmod/ml.md
        - 'Data Analysis': crossmod/analysis.md
    - Models: docs/models.md
theme: readthedocs